J2_appKeyVector				= MEM_OVERLAY + 3 * 0
J2_appOtherPressVec			= MEM_OVERLAY + 3 * 1
J2_process2				= MEM_OVERLAY + 3 * 2
J2_process2b				= MEM_OVERLAY + 3 * 3
J2_pageBreak				= MEM_OVERLAY + 3 * 4
J2_pastePicture				= MEM_OVERLAY + 3 * 5
J2_render_XXX				= MEM_OVERLAY + 3 * 6
J2_selectionProcess			= MEM_OVERLAY + 3 * 7
J2_mouseScrollUpDown			= MEM_OVERLAY + 3 * 8
J2_callbackJustification		= MEM_OVERLAY + 3 * 9
J2_selectPage				= MEM_OVERLAY + 3 * 10
J2_analyzeSelectionFont			= MEM_OVERLAY + 3 * 11
J2_blockSelectionProcess		= MEM_OVERLAY + 3 * 12

